-- ============================================================================
-- Production DB already has base tables — do NOT re-run CREATE statements here.
--
-- For any schema change, add a NEW file under supabase/migrations/ (e.g.
-- 002_something.sql) with only ALTER / RENAME / policies needed, then run that
-- file once in Supabase → SQL Editor.
--
-- Applied migrations in this repo:
--   migrations/001_album_visibility.sql
--   migrations/002_storage_portfolio_public_read.sql
--   migrations/003_homepage_slides.sql
-- ============================================================================
